In [1]:
import pandas as pd
with open(r"C:\Data-science\Practice_Data_Analytics\Datasets\messy_retail_dataset.csv") as f:
    data = pd.read_csv(f)
data

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,price,discount,order_date,delivery_days,payment_method,order_status,rating,review_text
0,7271,5076.0,Grace,Male,23.0,NaN,Mumbai,Food,Chair,5.0,1974.60,10.0,2021-04-22,9.0,Cash,Delivered,5.0,Average
1,861,1157.0,Charlie,M,57.0,France,Berlin,Furniture,Chair,9.0,1224.67,0.0,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor
2,5391,3717.0,Eva,F,43.0,UK,Paris,Food,Chair,NaN,1653.33,10.0,2021-04-05,6.0,NaN,Pending,3.0,Excellent
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,787.75,NaN,2022-04-04,6.0,Debit Card,Cancelled,3.0,Excellent
4,5192,1245.0,Alice,Female,23.0,India,New York,NaN,NaN,8.0,410.53,NaN,2021-01-03,9.0,UPI,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,Female,47.0,UK,NaN,Furniture,Phone,7.0,479.94,10.0,2023-04-19,1.0,UPI,Returned,5.0,Bad
19996,10381,1617.0,Alice,Female,41.0,UK,New York,Furniture,Laptop,8.0,337.10,0.0,2021-09-02,5.0,Credit Card,Pending,1.0,Excellent
19997,10686,5860.0,Charlie,M,48.0,Canada,New York,Food,Phone,1.0,706.87,NaN,2022-08-10,11.0,UPI,Cancelled,1.0,Bad
19998,3578,5144.0,Alice,Male,68.0,NaN,London,Electronics,NaN,5.0,1044.49,15.0,2022-03-30,10.0,Cash,NaN,5.0,NaN
19999,8381,1450.0,Grace,Female,69.0,NaN,New York,Books,Shirt,NaN,1921.45,15.0,2021-08-13,12.0,Debit Card,Returned,2.0,Poor

In [2]:
# copy of data for work 
df = data.copy()

# (1) - How many rows and columns are in the dataset?

In [3]:
df.shape
row , cols = df.shape
print(f"Rows:{row} , columns : {cols}")
# - 
len(df)
len(df.columns)

Rows:20000 , columns : 18

18


# (2) -What is the data type of each column?

In [4]:
df.dtypes
# detailed info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          20000 non-null  int64
 1   customer_id       19996 non-null  float64
 2   customer_name     17521 non-null  object
 3   gender            15963 non-null  object
 4   age               19677 non-null  float64
 5   country           17145 non-null  object
 6   city              17137 non-null  object
 7   product_category  16738 non-null  object
 8   product_name      17100 non-null  object
 9   quantity          17983 non-null  float64
 10  price             20000 non-null  float64
 11  discount          16576 non-null  float64
 12  order_date        20000 non-null  object
 13  delivery_days     18635 non-null  float64
 14  payment_method    16660 non-null  object
 15  order_status      16076 non-null  object
 16  rating            16729 non-null  float64
 17  review_text       16667 non-null  object
dtypes: float64(7), int64(1), object(10)
memory usage: 2.7+ MB

# (3) - Which columns contain missing values?

In [5]:
df.isna().any()
df.isnull().sum()
df.isna().sum()

# only columns that have actually have missing values
df.isna().sum()[df.isna().sum() > 0]

customer_id            4
customer_name       2479
gender              4037
age                  323
country             2855
city                2863
product_category    3262
product_name        2900
quantity            2017
discount            3424
delivery_days       1365
payment_method      3340
order_status        3924
rating              3271
review_text         3333
dtype: int64

# (4) - What percentage of data is missing in each column?

In [6]:
df.isna().sum() / 100

# only columns which have missing values
(df.isna().sum() / 100).loc[lambda x: x > 0]

customer_id          0.04
customer_name       24.79
gender              40.37
age                  3.23
country             28.55
city                28.63
product_category    32.62
product_name        29.00
quantity            20.17
discount            34.24
delivery_days       13.65
payment_method      33.40
order_status        39.24
rating              32.71
review_text         33.33
dtype: float64

# (5) - How many duplicate order_id values exist?

In [7]:
df.head(2)

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,price,discount,order_date,delivery_days,payment_method,order_status,rating,review_text
0,7271,5076.0,Grace,Male,23.0,NaN,Mumbai,Food,Chair,5.0,1974.60,10.0,2021-04-22,9.0,Cash,Delivered,5.0,Average
1,861,1157.0,Charlie,M,57.0,France,Berlin,Furniture,Chair,9.0,1224.67,0.0,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor

In [8]:
df['order_id'].duplicated().sum()
df['order_id'].duplicated(keep=False).sum()

np.int64(14700)

In [9]:
df['order_id'].duplicated(keep=False).sum()

np.int64(14700)

In [10]:
df['order_id'].nunique

<bound method IndexOpsMixin.nunique of 0         7271
1          861
2         5391
3        13419
4         5192
         ...
19995     6210
19996    10381
19997    10686
19998     3578
19999     8381
Name: order_id, Length: 20000, dtype: int64>

# (6) - How many unique customers are there?

In [11]:
df.head()
df['customer_name'].value_counts()
df['customer_name'].unique()
df['customer_name'].unique().size

8

# (7) - What are the unique values in gender?

In [12]:
df['gender'].unique()

array(['Male', 'M', 'F', nan, 'Female'], dtype=object)

# (8) - What are the unique values in order_status?

In [13]:
df['order_status'].unique()

array(['Delivered', 'Pending', 'Cancelled', nan, 'Returned'], dtype=object)

# (9) -Identify columns that should be categorical but are not.

In [14]:
df.dtypes
df.describe(include='object')

,customer_name,gender,country,city,product_category,product_name,order_date,payment_method,order_status,review_text
count,17521,15963,17145,17137,16738,17100,20000,16660,16076,16667
unique,7,4,6,6,5,6,900,5,4,5
top,Frank,Female,France,Toronto,Books,Shirt,2022-07-26,Net Banking,Cancelled,Good
freq,2562,4058,2909,2912,3433,2942,38,3414,4053,3377

# (10)- Identify columns that should be numerical but contain nulls or inconsistencies.

In [15]:
df.describe(include='int64')


import pandas as pd

# 1️⃣ View data types to spot numeric columns stored incorrectly (e.g., as object)
df.dtypes


# 2️⃣ Check missing values in numeric columns
# These columns SHOULD be numeric but already have nulls
numeric_nulls = df.select_dtypes(include='number').isna().sum()
numeric_nulls[numeric_nulls > 0]


# 3️⃣ Identify object columns that are mostly numeric
# These likely contain numbers mixed with strings like 'N/A', '-', etc.
object_cols = df.select_dtypes(include='object').columns

numeric_like = df[object_cols].apply(
    lambda col: pd.to_numeric(col, errors='coerce').notna().mean()
)

# Columns with >70% numeric values are strong candidates
numeric_like[numeric_like > 0.7]


# 4️⃣ Combine results to get final problematic columns
problematic_numeric_columns = list(
    set(numeric_nulls[numeric_nulls > 0].index)
    | set(numeric_like[numeric_like > 0.7].index)
)

problematic_numeric_columns


# 5️⃣ Quick statistical sanity check
# Look for odd min/max or missing counts
df[problematic_numeric_columns].describe(include='all')

,age,delivery_days,discount,quantity,customer_id,rating
count,19677.000000,18635.000000,16576.000000,17983.000000,19996.000000,16729.000000
mean,43.556538,7.488597,10.010859,4.971529,4494.462693,2.992588
std,14.914165,4.023346,7.040276,2.590734,2025.562373,1.415926
min,18.000000,1.000000,0.000000,1.000000,1000.000000,1.000000
25%,31.000000,4.000000,5.000000,3.000000,2744.000000,2.000000
50%,44.000000,7.000000,10.000000,5.000000,4475.000000,3.000000
75%,56.000000,11.000000,15.000000,7.000000,6266.250000,4.000000
max,69.000000,14.000000,20.000000,9.000000,7999.000000,5.000000

# (11) Remove or handle duplicate order_id records.

In [16]:
df['order_id'].duplicated().sum()
df_clean = df.drop_duplicates(subset='order_id', keep='last') #Option 1: Remove duplicates (keep last record)
df_clean = df[~df['order_id'].duplicated(keep=False)]       #Option 2: Remove all duplicates (keep only unique order_ids)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,price,discount,order_date,delivery_days,payment_method,order_status,rating,review_text
0,7271,5076.0,Grace,Male,23.0,NaN,Mumbai,Food,Chair,5.0,1974.60,10.0,2021-04-22,9.0,Cash,Delivered,5.0,Average
1,861,1157.0,Charlie,M,57.0,France,Berlin,Furniture,Chair,9.0,1224.67,0.0,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor
2,5391,3717.0,Eva,F,43.0,UK,Paris,Food,Chair,NaN,1653.33,10.0,2021-04-05,6.0,NaN,Pending,3.0,Excellent
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,787.75,NaN,2022-04-04,6.0,Debit Card,Cancelled,3.0,Excellent
4,5192,1245.0,Alice,Female,23.0,India,New York,NaN,NaN,8.0,410.53,NaN,2021-01-03,9.0,UPI,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,Female,47.0,UK,NaN,Furniture,Phone,7.0,479.94,10.0,2023-04-19,1.0,UPI,Returned,5.0,Bad
19996,10381,1617.0,Alice,Female,41.0,UK,New York,Furniture,Laptop,8.0,337.10,0.0,2021-09-02,5.0,Credit Card,Pending,1.0,Excellent
19997,10686,5860.0,Charlie,M,48.0,Canada,New York,Food,Phone,1.0,706.87,NaN,2022-08-10,11.0,UPI,Cancelled,1.0,Bad
19998,3578,5144.0,Alice,Male,68.0,NaN,London,Electronics,NaN,5.0,1044.49,15.0,2022-03-30,10.0,Cash,NaN,5.0,NaN
19999,8381,1450.0,Grace,Female,69.0,NaN,New York,Books,Shirt,NaN,1921.45,15.0,2021-08-13,12.0,Debit Card,Returned,2.0,Poor

# (12) -Standardize the gender column (M/F → Male/Female).

In [17]:
df['gender'].unique()
df['gender'] = df['gender'].replace({
    'M': 'Male',
    'Male': 'Male',
    'F': 'Female',
    'Female': 'Female'
})

# Even better (handles lowercase too)

df['gender'] = (
    df['gender']
    .str.strip()
    .str.upper()
    .replace({'M': 'Male', 'F': 'Female'})
)

# (13) - Handle missing values in age.

In [18]:
# df['age'].fillna(df['age'].mean() , inplace = True)
# forward fill 

df['age'] = df['age'].ffill()
df
df['age'].isna().sum()

np.int64(0)

# (14) -Handle missing values in quantity.

In [19]:
df.head(3)

# -- df['quantity'].isna().sum()
#  - df.fillna({'quantity' : df['quantity'].mean()})

# backward fill
df['quantity'] = df['quantity'].bfill()
df['quantity'].isna().sum()

np.int64(1)

# (15) -Handle missing values in price.

In [20]:
df['price'].fillna(df['price'].mean())
df['price'].isna

<bound method Series.isna of 0        1974.60
1        1224.67
2        1653.33
3         787.75
4         410.53
          ...
19995     479.94
19996     337.10
19997     706.87
19998    1044.49
19999    1921.45
Name: price, Length: 20000, dtype: float64>

# (16) - Replace null country values with “Unknown”.

In [21]:
# python logic 
#for i in range(len(df['country'])):
    #if df['country'][i] is None:
        #df['country'][i] = 'Unknown'




df['country'] = df['country'].fillna('Unknown')
df['country'].isna

<bound method Series.isna of 0        Unknown
1         France
2             UK
3         France
4          India
          ...
19995         UK
19996         UK
19997     Canada
19998    Unknown
19999    Unknown
Name: country, Length: 20000, dtype: object>

# (17) - Replace null city values logically based on country (if possible).

In [22]:
# df['city'].isna().sum()
city_by_country = (
    df.dropna(subset=['city'])
      .groupby('country')['city']
      .agg(lambda x: x.mode()[0])
)
df['city'] = df['city'].fillna(df['country'].map(city_by_country))
df['city'].isna().sum()

np.int64(0)

# (18) - Handle missing rating values.

In [23]:
df.tail(2)
df['rating'] = df['rating'].fillna(df['rating'].median())

# (19)- Drop rows where both customer_id and order_id are null.

In [24]:
df['customer_id'].dropna()
df.dropna(subset = ['order_id' , 'customer_id'])

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,price,discount,order_date,delivery_days,payment_method,order_status,rating,review_text
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,1974.60,10.0,2021-04-22,9.0,Cash,Delivered,5.0,Average
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,1224.67,0.0,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,1653.33,10.0,2021-04-05,6.0,NaN,Pending,3.0,Excellent
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,787.75,NaN,2022-04-04,6.0,Debit Card,Cancelled,3.0,Excellent
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,410.53,NaN,2021-01-03,9.0,UPI,NaN,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,479.94,10.0,2023-04-19,1.0,UPI,Returned,5.0,Bad
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,337.10,0.0,2021-09-02,5.0,Credit Card,Pending,1.0,Excellent
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,706.87,NaN,2022-08-10,11.0,UPI,Cancelled,1.0,Bad
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,1044.49,15.0,2022-03-30,10.0,Cash,NaN,5.0,NaN
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,1921.45,15.0,2021-08-13,12.0,Debit Card,Returned,2.0,Poor

# (20) - Clean the review_text column.

In [25]:
df['review_text'].bfill()
df['review_text'].isna().sum()

np.int64(3333)

# (21) Identify invalid ages (e.g., <18 or >70).

In [26]:
invalid_ages = df[(df['age'] < 18) | (df['age'] > 70)]
invalid_ages

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, country, city, product_category, product_name, quantity, price, discount, order_date, delivery_days, payment_method, order_status, rating, review_text]
Index: []

# (22) - Identify invalid quantities.

In [27]:
invalid_quantities = df[(df['quantity'] < 0) | (df['age'] > 50)]

# (23) - Identify negative or unrealistic prices (if any).

In [28]:
Negative_and_unrealistic_price = df[(df['price'] <= 0) | (df['price'] > 2000)]
Negative_and_unrealistic_price

Empty DataFrame
Columns: [order_id, customer_id, customer_name, gender, age, country, city, product_category, product_name, quantity, price, discount, order_date, delivery_days, payment_method, order_status, rating, review_text]
Index: []

# (24) - Convert order_date into year, month, and day columns.

In [29]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [30]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,discount,order_date,delivery_days,payment_method,order_status,rating,review_text,order_year,order_month,order_day
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,10.0,2021-04-22,9.0,Cash,Delivered,5.0,Average,2021,4,22
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,0.0,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor,2021,7,15
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,10.0,2021-04-05,6.0,NaN,Pending,3.0,Excellent,2021,4,5
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,NaN,2022-04-04,6.0,Debit Card,Cancelled,3.0,Excellent,2022,4,4
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,NaN,2021-01-03,9.0,UPI,NaN,4.0,NaN,2021,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,10.0,2023-04-19,1.0,UPI,Returned,5.0,Bad,2023,4,19
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,0.0,2021-09-02,5.0,Credit Card,Pending,1.0,Excellent,2021,9,2
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,NaN,2022-08-10,11.0,UPI,Cancelled,1.0,Bad,2022,8,10
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,15.0,2022-03-30,10.0,Cash,NaN,5.0,NaN,2022,3,30
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,15.0,2021-08-13,12.0,Debit Card,Returned,2.0,Poor,2021,8,13

# (25) - Create a cleaned version of the dataset.

In [31]:
Data = df.to_csv("Cleaned_data")

In [32]:
df.drop(columns = ['order_date'])

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,price,discount,delivery_days,payment_method,order_status,rating,review_text,order_year,order_month,order_day
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,1974.60,10.0,9.0,Cash,Delivered,5.0,Average,2021,4,22
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,1224.67,0.0,5.0,Credit Card,Delivered,1.0,Poor,2021,7,15
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,1653.33,10.0,6.0,NaN,Pending,3.0,Excellent,2021,4,5
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,787.75,NaN,6.0,Debit Card,Cancelled,3.0,Excellent,2022,4,4
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,410.53,NaN,9.0,UPI,NaN,4.0,NaN,2021,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,479.94,10.0,1.0,UPI,Returned,5.0,Bad,2023,4,19
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,337.10,0.0,5.0,Credit Card,Pending,1.0,Excellent,2021,9,2
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,706.87,NaN,11.0,UPI,Cancelled,1.0,Bad,2022,8,10
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,1044.49,15.0,10.0,Cash,NaN,5.0,NaN,2022,3,30
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,1921.45,15.0,12.0,Debit Card,Returned,2.0,Poor,2021,8,13

# (26) -Create a total_amount column (quantity × price).

In [40]:
df['total_amount'] = df['quantity'] * df['price']
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,order_date,delivery_days,payment_method,order_status,rating,review_text,order_year,order_month,order_day,total_amount
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,2021-04-22,9.0,Cash,Delivered,5.0,Average,2021,4,22,9873.00
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,2021-07-15,5.0,Credit Card,Delivered,1.0,Poor,2021,7,15,11022.03
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,2021-04-05,6.0,NaN,Pending,3.0,Excellent,2021,4,5,1653.33
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,2022-04-04,6.0,Debit Card,Cancelled,3.0,Excellent,2022,4,4,787.75
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,2021-01-03,9.0,UPI,NaN,4.0,NaN,2021,1,3,3284.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,2023-04-19,1.0,UPI,Returned,5.0,Bad,2023,4,19,3359.58
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,2021-09-02,5.0,Credit Card,Pending,1.0,Excellent,2021,9,2,2696.80
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,2022-08-10,11.0,UPI,Cancelled,1.0,Bad,2022,8,10,706.87
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,2022-03-30,10.0,Cash,NaN,5.0,NaN,2022,3,30,5222.45
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,2021-08-13,12.0,Debit Card,Returned,2.0,Poor,2021,8,13,NaN

# (27) - Create a discount_amount column.

In [45]:
#Safer version (handles missing discounts)
df['discount_amount'] = df['total_amount'] * (1 - df['discount'].fillna(0) / 100)

# if discount is a percentage
df['discount_amount'] = df['total_amount'] - (df['total_amount'] * df['discount'] / 100)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,delivery_days,payment_method,order_status,rating,review_text,order_year,order_month,order_day,total_amount,discount_amount
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,9.0,Cash,Delivered,5.0,Average,2021,4,22,9873.00,8885.7000
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,5.0,Credit Card,Delivered,1.0,Poor,2021,7,15,11022.03,11022.0300
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,6.0,NaN,Pending,3.0,Excellent,2021,4,5,1653.33,1487.9970
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,6.0,Debit Card,Cancelled,3.0,Excellent,2022,4,4,787.75,787.7500
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,9.0,UPI,NaN,4.0,NaN,2021,1,3,3284.24,3284.2400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,1.0,UPI,Returned,5.0,Bad,2023,4,19,3359.58,3023.6220
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,5.0,Credit Card,Pending,1.0,Excellent,2021,9,2,2696.80,2696.8000
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,11.0,UPI,Cancelled,1.0,Bad,2022,8,10,706.87,706.8700
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,10.0,Cash,NaN,5.0,NaN,2022,3,30,5222.45,4439.0825
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,12.0,Debit Card,Returned,2.0,Poor,2021,8,13,NaN,NaN

# (28)Create a final_amount after discount.

In [56]:
df['final_amount'] = df['total_amount'] - df['discount'].fillna(0)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,payment_method,order_status,rating,review_text,order_year,order_month,order_day,total_amount,discount_amount,final_amount
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,Cash,Delivered,5.0,Average,2021,4,22,9873.00,8885.7000,9863.00
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,Credit Card,Delivered,1.0,Poor,2021,7,15,11022.03,11022.0300,11022.03
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,NaN,Pending,3.0,Excellent,2021,4,5,1653.33,1487.9970,1643.33
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,Debit Card,Cancelled,3.0,Excellent,2022,4,4,787.75,787.7500,787.75
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,UPI,NaN,4.0,NaN,2021,1,3,3284.24,3284.2400,3284.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,UPI,Returned,5.0,Bad,2023,4,19,3359.58,3023.6220,3349.58
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,Credit Card,Pending,1.0,Excellent,2021,9,2,2696.80,2696.8000,2696.80
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,UPI,Cancelled,1.0,Bad,2022,8,10,706.87,706.8700,706.87
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,Cash,NaN,5.0,NaN,2022,3,30,5222.45,4439.0825,5207.45
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,Debit Card,Returned,2.0,Poor,2021,8,13,NaN,NaN,NaN

# (29) - Create an age_group column.

In [62]:
bins = [0,18,25,35,45,55,70]
labelss = ['<18','18-25','26-35','36-45','46-55','56-70' ]

df['age_group'] = pd.cut(df['age'] , bins=bins , labels = labels)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,order_status,rating,review_text,order_year,order_month,order_day,total_amount,discount_amount,final_amount,age_group
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,Delivered,5.0,Average,2021,4,22,9873.00,8885.7000,9863.00,18-25
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,Delivered,1.0,Poor,2021,7,15,11022.03,11022.0300,11022.03,56-70
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,Pending,3.0,Excellent,2021,4,5,1653.33,1487.9970,1643.33,36-45
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,Cancelled,3.0,Excellent,2022,4,4,787.75,787.7500,787.75,56-70
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,NaN,4.0,NaN,2021,1,3,3284.24,3284.2400,3284.24,18-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,Returned,5.0,Bad,2023,4,19,3359.58,3023.6220,3349.58,46-55
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,Pending,1.0,Excellent,2021,9,2,2696.80,2696.8000,2696.80,36-45
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,Cancelled,1.0,Bad,2022,8,10,706.87,706.8700,706.87,46-55
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,NaN,5.0,NaN,2022,3,30,5222.45,4439.0825,5207.45,56-70
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,Returned,2.0,Poor,2021,8,13,NaN,NaN,NaN,56-70

# (30) - Create a delivery_speed category using delivery_days.

In [70]:
bins = [0,3,7 , float('inf')]
labels = ['Faster_delivery' , 'Standard_delivery' , 'slower_delivery']

df['delivery_speed'] = pd.cut(df['delivery_days'], bins= bins , labels = labels)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,rating,review_text,order_year,order_month,order_day,total_amount,discount_amount,final_amount,age_group,delivery_speed
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,5.0,Average,2021,4,22,9873.00,8885.7000,9863.00,18-25,slower_delivery
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,1.0,Poor,2021,7,15,11022.03,11022.0300,11022.03,56-70,Standard_delivery
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,3.0,Excellent,2021,4,5,1653.33,1487.9970,1643.33,36-45,Standard_delivery
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,3.0,Excellent,2022,4,4,787.75,787.7500,787.75,56-70,Standard_delivery
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,4.0,NaN,2021,1,3,3284.24,3284.2400,3284.24,18-25,slower_delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,5.0,Bad,2023,4,19,3359.58,3023.6220,3349.58,46-55,Faster_delivery
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,1.0,Excellent,2021,9,2,2696.80,2696.8000,2696.80,36-45,Standard_delivery
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,1.0,Bad,2022,8,10,706.87,706.8700,706.87,46-55,slower_delivery
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,5.0,NaN,2022,3,30,5222.45,4439.0825,5207.45,56-70,slower_delivery
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,2.0,Poor,2021,8,13,NaN,NaN,NaN,56-70,slower_delivery

# (31) - Extract weekday from order_date.

In [91]:
data
data['order_date'] = pd.to_datetime(df['order_date'])
df['order_date'].dt.day_name()

# create a order day column using order_date
data['order_date'] = pd.to_datetime(data['order_date'], errors='coerce')
data['order_day'] = data['order_date'].dt.day_name()
data

df['order_date'].dt.day_name()

0         Thursday
1         Thursday
2           Monday
3           Monday
4           Sunday
           ...
19995    Wednesday
19996     Thursday
19997    Wednesday
19998    Wednesday
19999       Friday
Name: order_date, Length: 20000, dtype: object

# (32) - Create a flag column for “high value orders”.

In [93]:
df['high_value_order'] = (df['final_amount'] > 1000)
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,review_text,order_year,order_month,order_day,total_amount,discount_amount,final_amount,age_group,delivery_speed,high_value_order
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,Average,2021,4,Thursday,9873.00,8885.7000,9863.00,18-25,slower_delivery,True
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,Poor,2021,7,Thursday,11022.03,11022.0300,11022.03,56-70,Standard_delivery,True
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,Excellent,2021,4,Monday,1653.33,1487.9970,1643.33,36-45,Standard_delivery,True
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,Excellent,2022,4,Monday,787.75,787.7500,787.75,56-70,Standard_delivery,False
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,NaN,2021,1,Sunday,3284.24,3284.2400,3284.24,18-25,slower_delivery,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,Bad,2023,4,Wednesday,3359.58,3023.6220,3349.58,46-55,Faster_delivery,True
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,Excellent,2021,9,Thursday,2696.80,2696.8000,2696.80,36-45,Standard_delivery,True
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,Bad,2022,8,Wednesday,706.87,706.8700,706.87,46-55,slower_delivery,False
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,NaN,2022,3,Wednesday,5222.45,4439.0825,5207.45,56-70,slower_delivery,True
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,Poor,2021,8,Friday,NaN,NaN,NaN,56-70,slower_delivery,False

# (33) -Create a customer lifetime value metric.

In [96]:
customer_clv = df.groupby('customer_id')['final_amount'].sum().reset_index().rename(columns= {'final_amount' : 'Customer_lifetime_value'})
df = df.merge(customer_clv , on='customer_id', how='left')
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,order_month,order_day,total_amount,discount_amount,final_amount,age_group,delivery_speed,high_value_order,Customer_lifetime_value_x,Customer_lifetime_value_y
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,4,Thursday,9873.00,8885.7000,9863.00,18-25,slower_delivery,True,33339.24,33339.24
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,7,Thursday,11022.03,11022.0300,11022.03,56-70,Standard_delivery,True,20073.50,20073.50
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,4,Monday,1653.33,1487.9970,1643.33,36-45,Standard_delivery,True,14504.52,14504.52
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,4,Monday,787.75,787.7500,787.75,56-70,Standard_delivery,False,12846.76,12846.76
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,1,Sunday,3284.24,3284.2400,3284.24,18-25,slower_delivery,True,20170.50,20170.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,4,Wednesday,3359.58,3023.6220,3349.58,46-55,Faster_delivery,True,7932.60,7932.60
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,9,Thursday,2696.80,2696.8000,2696.80,36-45,Standard_delivery,True,32234.14,32234.14
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,8,Wednesday,706.87,706.8700,706.87,46-55,slower_delivery,False,26348.37,26348.37
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,3,Wednesday,5222.45,4439.0825,5207.45,56-70,slower_delivery,True,6064.59,6064.59
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,8,Friday,NaN,NaN,NaN,56-70,slower_delivery,False,37834.85,37834.85

# (34) - Create a column for repeat customers.

In [98]:
df['Repeated_customer'] = df['customer_name'].where(df['customer_id'].duplicated(keep=False))
df

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,order_day,total_amount,discount_amount,final_amount,age_group,delivery_speed,high_value_order,Customer_lifetime_value_x,Customer_lifetime_value_y,Repeated_customer
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,Thursday,9873.00,8885.7000,9863.00,18-25,slower_delivery,True,33339.24,33339.24,Grace
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,Thursday,11022.03,11022.0300,11022.03,56-70,Standard_delivery,True,20073.50,20073.50,Charlie
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,Monday,1653.33,1487.9970,1643.33,36-45,Standard_delivery,True,14504.52,14504.52,Eva
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,Monday,787.75,787.7500,787.75,56-70,Standard_delivery,False,12846.76,12846.76,Eva
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,Sunday,3284.24,3284.2400,3284.24,18-25,slower_delivery,True,20170.50,20170.50,Alice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,Wednesday,3359.58,3023.6220,3349.58,46-55,Faster_delivery,True,7932.60,7932.60,Grace
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,Thursday,2696.80,2696.8000,2696.80,36-45,Standard_delivery,True,32234.14,32234.14,Alice
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,Wednesday,706.87,706.8700,706.87,46-55,slower_delivery,False,26348.37,26348.37,Charlie
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,Wednesday,5222.45,4439.0825,5207.45,56-70,slower_delivery,True,6064.59,6064.59,Alice
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,Friday,NaN,NaN,NaN,56-70,slower_delivery,False,37834.85,37834.85,Grace

# (35) Create a binary column for “review given”.

In [101]:
# column for positive review
df['Positive_review'] = (df['rating'] >= 4).astype(int)
df
# option 2 - based on review text column
df['positive_review'] = df['review_text'].str.contains(
    'good|great|excellent|amazing',
    case=False,
    na=False
).astype(int)

,order_id,customer_id,customer_name,gender,age,country,city,product_category,product_name,quantity,...,total_amount,discount_amount,final_amount,age_group,delivery_speed,high_value_order,Customer_lifetime_value_x,Customer_lifetime_value_y,Repeated_customer,Positive_review
0,7271,5076.0,Grace,MALE,23.0,Unknown,Mumbai,Food,Chair,5.0,...,9873.00,8885.7000,9863.00,18-25,slower_delivery,True,33339.24,33339.24,Grace,1
1,861,1157.0,Charlie,MALE,57.0,France,Berlin,Furniture,Chair,9.0,...,11022.03,11022.0300,11022.03,56-70,Standard_delivery,True,20073.50,20073.50,Charlie,0
2,5391,3717.0,Eva,FEMALE,43.0,UK,Paris,Food,Chair,1.0,...,1653.33,1487.9970,1643.33,36-45,Standard_delivery,True,14504.52,14504.52,Eva,0
3,13419,2970.0,Eva,NaN,66.0,France,Berlin,Food,NaN,1.0,...,787.75,787.7500,787.75,56-70,Standard_delivery,False,12846.76,12846.76,Eva,0
4,5192,1245.0,Alice,FEMALE,23.0,India,New York,NaN,NaN,8.0,...,3284.24,3284.2400,3284.24,18-25,slower_delivery,True,20170.50,20170.50,Alice,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,6210,2164.0,Grace,FEMALE,47.0,UK,New York,Furniture,Phone,7.0,...,3359.58,3023.6220,3349.58,46-55,Faster_delivery,True,7932.60,7932.60,Grace,1
19996,10381,1617.0,Alice,FEMALE,41.0,UK,New York,Furniture,Laptop,8.0,...,2696.80,2696.8000,2696.80,36-45,Standard_delivery,True,32234.14,32234.14,Alice,0
19997,10686,5860.0,Charlie,MALE,48.0,Canada,New York,Food,Phone,1.0,...,706.87,706.8700,706.87,46-55,slower_delivery,False,26348.37,26348.37,Charlie,0
19998,3578,5144.0,Alice,MALE,68.0,Unknown,London,Electronics,NaN,5.0,...,5222.45,4439.0825,5207.45,56-70,slower_delivery,True,6064.59,6064.59,Alice,1
19999,8381,1450.0,Grace,FEMALE,69.0,Unknown,New York,Books,Shirt,NaN,...,NaN,NaN,NaN,56-70,slower_delivery,False,37834.85,37834.85,Grace,0

# (36) - What is the average order value?

In [106]:

# safer method if duplicate value exist
avg_order_value = (
    df.groupby('order_id')['final_amount']
      .sum()
      .mean()
)

average_order_value = df['final_amount'].mean()
average_order_value

np.float64(4936.681854092704)

# (37) - What is the total revenue?

In [110]:
df.head()
df.columns
total_revenue = df['final_amount'].sum()
total_revenue

np.float64(98728700.39999999)

#  (38) - Revenue by product category.

In [115]:
revenue_by_product_category = (
    df.groupby('product_category')['final_amount'].sum()
)
revenue_by_product_category

product_category
Books          16987751.56
Clothing       15948142.49
Electronics    15984976.49
Food           16975251.82
Furniture      17171147.49
Name: final_amount, dtype: float64

# (39) - Revenue by country.

In [116]:
Revenue_by_country = ( 
    df.groupby('country')['final_amount'].sum()
)
Revenue_by_country

country
Canada     13927398.13
France     14023769.26
Germany    13846913.47
India      13987846.59
UK         14349580.15
USA        14599265.10
Unknown    13993927.70
Name: final_amount, dtype: float64

# (40) - Top 10 cities by revenue.

In [118]:
top_10_cities_by_revenue = (
    df.groupby('city')['final_amount'].sum().sort_values(ascending=False).head(10)
)
top_10_cities_by_revenue

city
Toronto     22523744.64
New York    16558772.45
Mumbai      16395339.15
London      15556745.55
Paris       14223621.59
Berlin      13470477.02
Name: final_amount, dtype: float64

 # (41) - Average rating per product category.

In [121]:
avg_rating_per_product_category = (
    df.groupby('product_category')['rating'].mean()
)
avg_rating_per_product_category

product_category
Books          2.990679
Clothing       2.983925
Electronics    3.022045
Food           2.974382
Furniture      2.978482
Name: rating, dtype: float64

 # (42) - Order count per payment method.

In [124]:
# -- count each rows 
order_count_per_payment = (
    df.groupby('payment_method')['order_id'].count()
)
order_count_per_payment

# use nunique is duplicate exist 
order_count_per_payment = (
    df.groupby('payment_method')['order_id']
      .nunique()
)
order_count_per_payment

payment_method
Cash           2990
Credit Card    3022
Debit Card     2886
Net Banking    3058
UPI            2958
Name: order_id, dtype: int64

# (43) - Cancellation rate by country.

In [141]:
cancellation_rate_by_country = (
    df.groupby('country').apply(lambda x: (x['order_status'] == 'Cancelled').sum() / len(x) * 100).round(2)
)

cancellation_rate_by_country

C:\Users\javedshaik\AppData\Local\Temp\ipykernel_7188\1632328197.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('country').apply(lambda x: (x['order_status'] == 'Cancelled').sum() / len(x) * 100).round(2)

country
Canada     20.52
France     21.42
Germany    19.85
India      19.26
UK         19.66
USA        19.90
Unknown    21.23
dtype: float64

# (44) - Return rate by product category.

In [148]:
raturn_rate_product_by_category = (
    df.groupby('product_category').apply(lambda x: (x['order_status'] == 'Returned').sum() / len(x))
)

raturn_rate_product_by_category

C:\Users\javedshaik\AppData\Local\Temp\ipykernel_7188\2595676647.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('product_category').apply(lambda x: (x['order_status'] == 'Returned').sum() / len(x))

product_category
Books          0.206525
Clothing       0.207158
Electronics    0.190753
Food           0.207008
Furniture      0.190974
dtype: float64

# (45) Average delivery time per country.

In [150]:
average_delivery_time = (
    df.groupby('country', as_index=False)['delivery_days']
      .mean()
      .round(2)
)

average_delivery_time

   country  delivery_days
0   Canada           7.54
1   France           7.35
2  Germany           7.40
3    India           7.48
4       UK           7.57
5      USA           7.60
6  Unknown           7.47

# (46) - Which age group spends the most?

In [152]:
most_spend_age_group = (
    df.groupby('age_group', as_index = False)['final_amount'].sum()
)
most_spend_age_group

C:\Users\javedshaik\AppData\Local\Temp\ipykernel_7188\1916660271.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_group', as_index = False)['final_amount'].sum()

  age_group  final_amount
0       <18    1976998.13
1     18-25   13092173.87
2     26-35   18599986.67
3     36-45   19228805.05
4     46-55   19073377.17
5     56-70   26757359.51

# (47) - Gender-wise spending comparison.

In [155]:
gender_wise_spending_comparison = (
    df.groupby('gender', as_index = False)['final_amount'].sum()
)
gender_wise_spending_comparison

   gender  final_amount
0  FEMALE   40280181.13
1    MALE   38511678.36

# (48) - Monthly sales trend.

In [162]:
monthly_sales_trend = (
    df.groupby(['order_year', 'order_month'])['final_amount']
      .sum()
      .reset_index()
)
monthly_sales_trend

    order_year  order_month  final_amount
0         2021            1    3477774.83
1         2021            2    3366723.22
2         2021            3    3440730.65
3         2021            4    3312619.14
4         2021            5    3648020.21
5         2021            6    3240312.92
6         2021            7    3479739.45
7         2021            8    3723203.04
8         2021            9    3299909.23
9         2021           10    3239150.44
10        2021           11    3351280.07
11        2021           12    3786803.12
12        2022            1    3381568.91
13        2022            2    2914662.96
14        2022            3    3098789.56
15        2022            4    3104024.09
16        2022            5    3338389.33
17        2022            6    3280138.78
18        2022            7    3421123.64
19        2022            8    3186691.19
20        2022            9    3264222.18
21        2022           10    3166528.16
22        2022           11    3047407.45
23        2022           12    3630678.54
24        2023            1    3458775.93
25        2023            2    3043525.27
26        2023            3    3459936.34
27        2023            4    3270826.54
28        2023            5    3332942.04
29        2023            6    1962203.17

# (49) - Identify peak sales month.

In [170]:
monthly_sales = (
    df.groupby('order_month' , as_index = False)['final_amount'].sum()
)

#highest_month_sale = monthly_sales.idxmax() 
#highest_month_sale
monthly_sales

    order_month  final_amount
0             1   10318119.67
1             2    9324911.45
2             3    9999456.55
3             4    9687469.77
4             5   10319351.58
5             6    8482654.87
6             7    6900863.09
7             8    6909894.23
8             9    6564131.41
9            10    6405678.60
10           11    6398687.52
11           12    7417481.66

# (50) - Identify worst-performing product category.

In [173]:
# Revenue by category
revenue_by_category = (
    df.groupby('product_category')['final_amount'].sum()
)
wrost_performing_category = revenue_by_category.idxmin()
wrost_performing_category
print(f" {wrost_performing_category} : is the wrost performing category .")

 Clothing : is the wrost performing category .